---
name: POE-Session-Moose
version: 0.01
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
abstract: A POE::Session implementation as a Moose::Role
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
build_requires:
  Moose: 0.75
  MooseX::Declare: 0.1
  POE: 1.004
  Test::More: 0
provides:
  POE::Session::Moose:
    file: lib/POE/Session/Moose.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
