---
name: POEx-Role-SessionInstantiation
version: 0.01
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
abstract: A POE::Session implementation as a Moose::Role
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://nickandperla.net/pxrsi.git/
build_requires:
  MooseX::Declare: 0.2
  POE: 1.005
  Test::More: 0
provides:
  POEx::Role::SessionInstantiation:
    file: lib/POEx/Role/SessionInstantiation.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
